### ISSUE TITLE
Number of decimal places should be limited in tooltips

### ISSUE THREAD

**Issue by dvoits** [predictionmachines/InteractiveDataDisplay#10]
How to reproduce:
1. Open idd sample [Simple Line Chart]( http://predictionmachines.github.io/InteractiveDataDisplay/sample-line.html)
2. Hover mouse over a blue line.
3. Get a tooltip after a few seconds.

Expected: Coordinates of the cursor should be like "0.75, 0.69" for the given axis ranges.
Observed: Coordinates are of maximum double precision. See the screenshot:
![image](https://cloud.githubusercontent.com/assets/4416154/11400278/6f107ffc-939d-11e5-981b-643c2465a3bc.png)

**Comment by msdvoits** [comment]
@sergey-berezin I thought you did it already, isn't it?
