### ISSUE TITLE
Bing map plot containing samples sometimes do not work

### ISSUE THREAD

**Issue by dgrechka** [predictionmachines/InteractiveDataDisplay#139]
Occasionally (the race condition issue), when bing map plot containing sample is loaded, the map is not shown and the console contains the following error:

![image](https://user-images.githubusercontent.com/5637547/32598798-b2ee4966-c54b-11e7-8b6a-11c9048077fe.png)

**Comment by dgrechka** [comment]
The cause of the issue is that $(document).ready event fires before bing map control javascript library is loaded and initialized.

As Idd bing map plot is initialized in $(document).ready it uses variables of bing maps SDK, the variables may be not ready yet.

In case of initialization of Bing SDK happens earlier than document.ready everything works fine.
Otherwise the map plot initialization fails

**Comment by sergey-b-berezin** [comment]
Fixed by 88864af614f366579ffdf9ef7ccfd8f8575f9c27
