### ISSUE TITLE
request: NPM registry

### ISSUE THREAD

**Issue by cgravill** [predictionmachines/InteractiveDataDisplay#141]
Given Bower is in maintenance mode (https://bower.io/blog/2017/how-to-migrate-away-from-bower/) and not recommended for new projects could you deploy to NPM please? The compatibility for the Bower repository was dropped from e.g. Yarn and other tools making it harder to obtain and use IDD.

**Comment by cgravill** [comment]
The release notes for 1.5.1 actually mention deploying to npm. Is on there? https://www.npmjs.com/package/idd is definitely something else, and I'm not finding "interactive-data-display" which is in the package.json

**Comment by dgrechka** [comment]
published on NPM: https://www.npmjs.com/package/interactive-data-display
