### ISSUE TITLE
idd.umd.d.ts & TypeScript 3.0.1

### ISSUE THREAD

**Issue by cgravill** [predictionmachines/InteractiveDataDisplay#153]
Using the dist folder from release v1.5.12 and TypeScript 3.0.1 I get this error:

error TS2714: Build:The expression of an export assignment must be an identifier or qualified name in an ambient context.

I don't use UMD on that project so can workaround it by excluding the files.

**Comment by dgrechka** [comment]
This one resolved in [release 1.5.38](https://github.com/predictionmachines/InteractiveDataDisplay/blob/master/RELEASE_NOTES.md#1538-february-13-2020)
