### ISSUE TITLE
Scientific notation for axis labels

### ISSUE THREAD

**Issue by ndalchau** [predictionmachines/InteractiveDataDisplay#157]
When the values of axes labels are large, scientific notation is adopted, but currently uses the 'e' format. e.g. 1.2e+5. While this representation is clearly convenient, it is not a common representation of such large numbers. Rather, it is more customary to write large numbers as 1.2 x 10<sup>5</sup>.

In Matlab, linear-scale axes show the 10<sup>5</sup> at the top of the axis, which I think is rather strange:
![image](https://user-images.githubusercontent.com/7451485/49805325-c5a3fa80-fd4c-11e8-8ff0-027dc77c1265.png)
However, their log-scale axes are really nice:
![image](https://user-images.githubusercontent.com/7451485/49805588-5ed31100-fd4d-11e8-8bef-4fb65f8183d6.png)

Either way, the rendering of large numbers adopts the superscript format. 

Would it be possible to use superscript form in IDD?

**Comment by dgrechka** [comment]
The feature has been added in fcfd0d5a but not used as a default in IDD yet.

However in [FSharpIDD](/predictionmachines/FSharpIDD) the scientific notation is used by default  starting from v0.3.2
