### ISSUE TITLE
Angled labels doesn't seem to work on a labelled axis

### ISSUE THREAD

**Issue by lucymukh** [predictionmachines/InteractiveDataDisplay#161]
Unable to tilt labels on a labelled axis when number of ticks equals number of labels.
However when number of labels is one fewer than number of ticks, labels are tilted properly.

**Comment by dgrechka** [comment]
@ndalchau confirms this in FSharpIDD:

Chart.Empty
|> Chart.addMarkers (Markers.createMarkers xs means)
|> Chart.setXaxis (Chart.createTiltedLabelledAxis xs xticks 90.0)

![image](https://user-images.githubusercontent.com/5637547/53002329-8aedcb00-343d-11e9-823c-d2643b63d37f.png)
