### ISSUE TITLE
Area plot SVG representation are grayscale in Inkscape

### ISSUE THREAD

**Issue by dgrechka** [predictionmachines/InteractiveDataDisplay#172]
Exporting SVG representation of area plots and opening them in Inkscape causes colours with transperency to be turned into a grayscale:
![image](https://user-images.githubusercontent.com/5637547/52397102-4cfbb900-2ac5-11e9-9ac9-8e2504f06c88.png)
Where expected picture is:
![image](https://user-images.githubusercontent.com/5637547/52397128-6270e300-2ac5-11e9-9021-407faa5431fd.png)

**Comment by dgrechka** [comment]
This reproduces if the fill colour of the area plot is set in rgba fromat. E.g. rgba(0, 0, 255, 0.2)

ExportToSVG of area plot addes hardcoded opacity(0.5) attribute.
The combination of rgba colour defeiniton and opacity causes grayscale in some SVG viewers.

**Comment by dgrechka** [comment]
According to SVG color specification: https://www.w3.org/TR/SVGColor12/#Color_syntax

The rgba format is not supported in SVG.
As IDD injects CSS color into SVG as is, this causes the issue,

**Comment by sergey-berezin** [comment]
The solution could be splitting IDD color into two SVG properties: 'fill' and ['fill-opacity'](https://www.w3.org/TR/SVG11/painting.html#FillProperties).

**Comment by dgrechka** [comment]
Yep!
I'm extending InteractiveDataDisplay.ColorPalette.colorFromString to support rgba format right now.

Will use this function to split the "transparent color" into color and opacity to set them in SVG.
