### ISSUE TITLE
idd.umd dependencies

### ISSUE THREAD

**Issue by FilippoPolo** [predictionmachines/InteractiveDataDisplay#190]
Hi all,

I'd like to import IDD in a React project created with Create React App. This is a framework that relies on webpack, but hides most of webpack's configuration complexity, so it's not very configurable; it relies on people adhering strictly to some standards. I also would like to handle all dependencies through the module system (i.e. not through <script> tags in HTML), because this will allow me to make the project easily reusable.

CRA's webpack configuration won't allow me to load idd as a global; it only handles modules. So I used idd.umd.js. But I'm having problems with some of the imports.

There's no require.config in this type of project; I'm supposed to use the npm module names instead. Specifically: the "svg" module is actually called "svg.js", and "filesaver" is actually "file-saver".

Also, I'm not sure about "css!idd-css". Even if I had the css! extension, there's no file called idd-css in the distribution. In any case, in this context I don't have extensions, but I do have CSS modules support, so the "correct" import would be "./idd.umd.css".

Would you consider changing the names in the define call to their respective npm module names, as described above? This will allow people to use ES6 imports with webpack without any additional configuration, while any require users can just change the names in config.

I'm not sure about what to do with the CSS import, because the correct form depends on what bundler is being used. If the "css!" form must be preserved, I guess we could do a separate idd.webpack.js file with the more recent form.

**Comment by dgrechka** [comment]
Hi Filippo,

Am I right that we need to update only 3 module names:
* filesaver -> file-saver
* svg -> svg.js
* css!idd-css -> ./idd.umd.css

Let's use another bundle idd.webpack.js not to brake the existing rules. I believe the existing rules handles css!idd-css with proper require.config.

If you confirm the rename list, I'll add this additional bundle file and publish the new release.

**Comment by FilippoPolo** [comment]
That is correct. This is my modified define call:

		define(['jquery', 'rx', 'svg.js', 'file-saver', './idd.umd.css', 'jquery-ui', 'jquery-mousewheel'], 

With that, I can use IDD in Create React App.

A separate bundle would be fine; I too think it's the best solution.

**Comment by dgrechka** [comment]
resolved in a53e3e3a909b.
Published in NPM in v1.5.31

@FilippoPolo , you can use new distributed bundle file **idd.webpack.js**.
