### ISSUE TITLE
Simple markers sample does not work in Chrome

### ISSUE THREAD

**Issue by dgrechka** [predictionmachines/InteractiveDataDisplay#2]
Simple markers looks wrong in Chrome browser.

![image](https://cloud.githubusercontent.com/assets/5637547/9891378/8fa277d2-5c0e-11e5-92e5-7d9b7bdaa6fe.png)

Chrome Version 45.0.2454.93 m

**Comment by ElenaPochernina** [comment]
It is already fixed.
