### ISSUE TITLE
Bower.json: "main" element doesn't satisfy the specification

### ISSUE THREAD

**Issue by msdvoits** [predictionmachines/InteractiveDataDisplay#21]
The bower documentation: https://github.com/bower/spec/blob/master/json.md#main
In particular, it is said **Only one file per filetype**. 

The "main" of IDD's bower.json includes two *.js files.

**Comment by msdvoits** [comment]
We should find the appropriate solution: whether we should merge the files into a single one, or introduce another one which imports both files?

**Comment by dgrechka** [comment]
We don't distribute IDD through bower anymore.
FYI: The main file for NPM is **idd.webpack** now
