### ISSUE TITLE
Chart Viewer navigation in Mozilla Firefox 45.0.2

### ISSUE THREAD

**Issue by ElenaPochernina** [predictionmachines/InteractiveDataDisplay#43]
Open sample `samples/viewer/Band.html`.
Unlock navigation (on right navigation panel).
Add a probe on chart.
Now you can zoom a chart regardless of the position of cursor (left panel, right panel, under the chart).
It is expected that you can zoom chart only when the cursor is on chart.

**Comment by dgrechka** [comment]
Does not reproduce on FF Version 64.0.2 (64-bit) Windows.
Seems to be resolved
