### ISSUE TITLE
How to destroy the IDD navigation panel?

### ISSUE THREAD

**Issue by msdvoits** [predictionmachines/InteractiveDataDisplay#44]
@ElenaPochernina, I see that in the NavigationPanel there is no "remove" method (or "destroy", "dispose") which would unsubscribe it from events and clear the DOM object.

In the sample you just create an object and don't even keep the reference to it. Still I might want to remove the panel if show it dynamically on my page.

```
        $(document).ready(function () {  
            var chart = InteractiveDataDisplay.asPlot($("#chart"));  
            var navigation = $('#navigationPanel');  
            InteractiveDataDisplay.NavigationPanel(chart, navigation);  
```

The suggestion is to add the `NavigationPanel.remove()` method which unsubscribe it from events and clears the DOM object.

**Comment by ElenaPochernina** [comment]
I did it in branch `legend`

**Comment by msdvoits** [comment]
Ok, I see, there is the 'remove()' method:

```
navigation.remove();
```
