### ISSUE TITLE
Wiki for "Area" has mistakes

### ISSUE THREAD

**Issue by dvoits** [predictionmachines/InteractiveDataDisplay#76]
@ElenaPochernina Please see https://github.com/predictionmachines/InteractiveDataDisplay/wiki/Area:
1. Section "Html" is just a copy of the sample for a polyline.
2. Sample in "JavaScript" can use name "area" instead of "band".
3. It would be better if ChartViewer would use "area" instead of "band".

**Comment by dgrechka** [comment]
Seems to be resolved long ago
