### ISSUE TITLE
Markers: drawing an empty array doesn't clear previous image

### ISSUE THREAD

**Issue by dvoits** [predictionmachines/InteractiveDataDisplay#8]
**How to reproduce:**
1. Create a chart with markers plot
2. Call `markers.draw({x:[1,2,3], y:[1,2,3]})`. You should see three markers in a chart.
3. Call `markers.draw({x:[], y:[])`. 

**Expected:** chart without any marker

**Observed:** three markers; same image as after step 2.

**Workaround:** To clear markers, call `markers.getContext(true)`. This is safe since has no side effects except clearing the screen.

**Comment by msdvoits** [comment]
It looks like that is already fixed after marker reconstruction. I'll check that.
