### ISSUE TITLE
Bull-eyes and petals are gray when loaded in Inkscape

### ISSUE THREAD

**Issue by dvoits** [predictionmachines/InteractiveDataDisplay#94]
1. Open the Angara.Chart documentation page: http://predictionmachines.github.io/Angara.Chart/
2. Find the Bull-eyes sample 
3. Click download as svg button at the chart panel
4. Open the downloaded svg file in the Inkscape

Expected: the plot has colors, as when open in Edge
Observed: the plot is black
![image](https://cloud.githubusercontent.com/assets/4416154/19803540/f9013fac-9d11-11e6-851e-b8949bb1b5e5.png)

**Comment by ElenaPochernina** [comment]
Inkscape doesn't support color in format "rgba(r, g, b, a)". But in all browsers (Mozilla, Edge, Chrome, Safari, IE) the plot has colors.
